alias vim="/usr/local/bin/nvim"
alias rm="rm -i"
alias U="cd .."
alias cp="cp -ip"
alias mv="mv -i"
alias l="eza -lgho --sort=modified --icons --git --git-repos"
alias ls="eza -lgho --sort=modified  --icons --git --git-repos"
alias ll="eza -lgho --sort=modified --icons --git --git-repos"
alias pp="ping -c 3 google.com"
alias space="sudo du -h --max-depth=1 -t 1G"
alias dot="yadm pull"
alias docker-restart="docker restart $(docker ps -a -q)"
alias dockerrun="sudo docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}'"
alias dockerlogs="sudo docker compose logs -f"
alias takeover="sudo chown -R ecloaiza:ecloaiza *"
alias fixperm="sudo chmod -R 775 *"
alias idrive="/opt/IDriveForLinux/bin/idrive"
alias sudoers="/home/ecloaiza/scripts/linux/install-sudoers.sh"
alias syncn='rsync -a --exclude=".git" --include="*/" --exclude="*" /home/ecloaiza/devops/github/ /home/ecloaiza/Documents/Obsidian/Loaiza/IT/github/ && unison obsidian_sync && find /home/ecloaiza/devops/github -mindepth 1 -depth -type d -empty -delete'
alias syncs='/home/ecloaiza/scripts/linux/sudoers/sync-sudoers.sh'
alias sync_claude='unison claude_skills'
