alias vim="vi"
alias rm="rm -i"
alias U="cd .."
alias ls="ls -l --color=yes | less -r -E -X"
alias cp="cp -ip"
alias mv="mv -i"
alias ll="ls -A | less -r -E -X"
alias pp="ping -c 3 google.com"
alias l="ll"
alias space="sudo du -h --max-depth=1"
alias ls='exa --icons -F -H --group-directories-first'