alias vim="vi"
alias rm="rm -i"
alias U="cd .."
alias ls="ls -l --color=yes | less -r -E -X"
alias cp="cp -ip"
alias mv="mv -i"
alias ll="ls -l | less -r -E -X"
alias pp="ping -c 3 google.com"
alias l="ls -l | less -r -E -X"
alias space="sudo du -h --max-depth=1 -t 1G"
alias ls='exa --icons -F -H --group-directories-first'
alias dot="yadm pull"
alias docker-restart="docker restart $(docker ps -a -q)"
alias dockerrun="sudo docker ps --format 'table {{.ID}}\t{{.Names}}\t{{.Status}}'"
alias dockerlogs="sudo docker compose logs -f"
alias takeover="sudo chown -R ecloaiza:ecloaiza *"
alias fixperm="sudo chmod -R 775 *"
alias vim="nvim"
