#!/bin/bash

# ==============================================================================
# UniFi Gateway Certificate Deploy Script
# Executed by Certbot on the Ubuntu Client after a successful renewal.
# ==============================================================================

# --- CONFIGURATION ---

# The IP address or Hostname of your UniFi Gateway
UNIFI_HOST="192.168.5.1"

# The SSH Username for your UniFi Gateway (usually 'root')
UNIFI_USER="root"

# SSH via Proton Pass SSH agent (key: "UniFi Router SSH Key - RSA" in HOMELAB vault)
export SSH_AUTH_SOCK="/home/ecloaiza/.ssh/proton-pass-agent.sock"

# Path to the certificate and key generated by Certbot (Passed automatically by Certbot)
CERT_PATH="${RENEWED_LINEAGE}/fullchain.pem"
KEY_PATH="${RENEWED_LINEAGE}/privkey.pem"

# --- DEPLOYMENT LOGIC ---

echo "--- Starting UniFi Certificate Deployment ---"
echo "Target: ${UNIFI_USER}@${UNIFI_HOST}"

# Check if certificate files exist
if [[ ! -f "$CERT_PATH" ]] || [[ ! -f "$KEY_PATH" ]]; then
  echo "Error: Certificate files not found at expected path."
  exit 1
fi

# 1. Upload Certificate and Key to UniFi Gateway
echo "Uploading certificates to /tmp/..."
scp -o StrictHostKeyChecking=no -q "$CERT_PATH" "${UNIFI_USER}@${UNIFI_HOST}:/tmp/unifi-core.crt"
scp -o StrictHostKeyChecking=no -q "$KEY_PATH" "${UNIFI_USER}@${UNIFI_HOST}:/tmp/unifi-core.key"

if [ $? -ne 0 ]; then
  echo "Error: SCP upload failed. Check SSH connectivity and keys."
  exit 1
fi

# 2. Move files to correct location and restart service
echo "Installing certificates and restarting UniFi Core..."
ssh -o StrictHostKeyChecking=no "${UNIFI_USER}@${UNIFI_HOST}" "bash -s" <<EOF

    # Define the target directory (Standard for UniFi OS 1.x, 2.x, 3.x)
    TARGET_DIR="/data/unifi-core/config"
    
    # Backup existing certificates
    if [ -f "\$TARGET_DIR/unifi-core.crt" ]; then
        cp "\$TARGET_DIR/unifi-core.crt" "\$TARGET_DIR/unifi-core.crt.bak"
    fi
    if [ -f "\$TARGET_DIR/unifi-core.key" ]; then
        cp "\$TARGET_DIR/unifi-core.key" "\$TARGET_DIR/unifi-core.key.bak"
    fi

    # Move new certificates into place
    mv /tmp/unifi-core.crt "\$TARGET_DIR/unifi-core.crt"
    mv /tmp/unifi-core.key "\$TARGET_DIR/unifi-core.key"

    # Set permissions (Critical for UniFi OS to read them)
    chmod 644 "\$TARGET_DIR/unifi-core.crt"
    chmod 600 "\$TARGET_DIR/unifi-core.key"

    # Restart the UniFi Core service to apply changes
    echo "Restarting unifi-core service..."
    systemctl restart unifi-core

EOF

if [ $? -eq 0 ]; then
  echo "--- Deployment Successful! ---"
else
  echo "Error: Remote command execution failed."
  exit 1
fi
