# renew_before_expiry = 30 days
version = 2.9.0
archive_dir = /home/ecloaiza/scripts/certbot/config/archive/router.home.elikesbikes.com
cert = /home/ecloaiza/scripts/certbot/config/live/router.home.elikesbikes.com/cert.pem
privkey = /home/ecloaiza/scripts/certbot/config/live/router.home.elikesbikes.com/privkey.pem
chain = /home/ecloaiza/scripts/certbot/config/live/router.home.elikesbikes.com/chain.pem
fullchain = /home/ecloaiza/scripts/certbot/config/live/router.home.elikesbikes.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 3027feb21f21e1d032e471da7b1dc57d
renew_hook = /home/ecloaiza/scripts/certbot/hooks/deploy_to_unifi.sh
config_dir = /home/ecloaiza/scripts/certbot/config
work_dir = /home/ecloaiza/scripts/certbot/work
logs_dir = /home/ecloaiza/scripts/certbot/logs
authenticator = dns-cloudflare
dns_cloudflare_credentials = /home/ecloaiza/.secrets/certbot/cloudflare.ini
server = https://acme-v02.api.letsencrypt.org/directory
key_type = rsa
